export const NEXT_STOCK = 'NEXT_STOCK';
export const PREV_STOCK = 'PREV_STOCK';
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY';
export const UPDATE_CURRENCY_RATE = 'UPDATE_CURRENCY_RATE';
export const UPDATE_TIMES = 'UPDATE_TIMES';